image: node:alpine

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g gulp

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install

test:
  stage: test
  script:
    - npm test